In [4]:
import numpy as np
 

In [5]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr = np.ones((3,6))


In [7]:
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [6]:
arr.dtype

dtype('float64')

In [10]:
l = [2, 3, 3, 23, 0, 1]

In [15]:
type(l)

list

In [16]:
np_arr = np.array(l)

In [10]:
np_arr.dtype

dtype('int32')

In [17]:
a = np.array([[1,2,3,], [4,5,6], [7,8,9]])

In [18]:
b = np.array([[9,2,3], [7,-2,9], [4,16,36]]) 

In [15]:
data = np.random.randn(7, 4)

In [16]:
data

array([[-0.38071706, -0.38719304, -0.88761729, -0.7389692 ],
       [ 0.85783222, -0.85082901,  1.4460639 ,  0.93482141],
       [ 1.47619401, -0.14555633,  1.09673305, -0.90793658],
       [ 1.01627831,  1.09224791,  0.83510819,  1.87888212],
       [-0.50443133, -0.13449301, -0.28170048, -0.04516149],
       [-0.10499019, -0.4455902 ,  1.35858187,  1.00196678],
       [ 1.48111235, -0.25001772,  1.34331758, -1.87230793]])

In [17]:
data

array([[-0.38071706, -0.38719304, -0.88761729, -0.7389692 ],
       [ 0.85783222, -0.85082901,  1.4460639 ,  0.93482141],
       [ 1.47619401, -0.14555633,  1.09673305, -0.90793658],
       [ 1.01627831,  1.09224791,  0.83510819,  1.87888212],
       [-0.50443133, -0.13449301, -0.28170048, -0.04516149],
       [-0.10499019, -0.4455902 ,  1.35858187,  1.00196678],
       [ 1.48111235, -0.25001772,  1.34331758, -1.87230793]])

In [20]:
a.shape

(3, 3)

In [23]:
b.shape

(4, 3)

In [24]:
b= b.reshape(3,4)

In [25]:
b.shape

(3, 4)

In [26]:
a.dot(b)

array([[113,  44,  38,  48],
       [242, 101,  86, 126],
       [371, 158, 134, 204]])

In [33]:
b = b.T

In [31]:
b.shape


(3, 4)

In [34]:
b.dot(a)

array([[253, 296, 339],
       [ 94, 113, 132],
       [ 82,  98, 114],
       [ 92, 118, 144]])

In [36]:
a.sum()

45

In [19]:
np.add(b,a)

array([[10,  4,  6],
       [11,  3, 15],
       [11, 24, 45]])

In [21]:
np.multiply(a,b)

array([[  9,   4,   9],
       [ 28, -10,  54],
       [ 28, 128, 324]])

In [22]:
np.sqrt(b)

C:\Users\EMPEROR\AppData\Local\Temp\ipykernel_6068\3240365511.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(b)


array([[3.        , 1.41421356, 1.73205081],
       [2.64575131,        nan, 3.        ],
       [2.        , 4.        , 6.        ]])

In [23]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [24]:
a + b


array([[10,  4,  6],
       [11,  3, 15],
       [11, 24, 45]])